### ISSUE TITLE
Datepicker doesn't work

### ISSUE THREAD

**Issue by dumblob** [martykan/odorik#1]
There are about 10 JavaScript errors. But the most important one causes the datepicker to not work at all:

![20201109_113609+0100-1680x1050+0+0-imlib2_grab](https://user-images.githubusercontent.com/2451044/98531298-6d4f3d80-2280-11eb-8c9c-9b581fd388d5.png)

(`...daterangepicker is not a function`)

**Comment by martykan** [comment]
The datepicker library is loaded externally to make the app available in a single file. 
You are probably blocking requests to that resource, so you need to whitelist it.

**Comment by dumblob** [comment]
>The datepicker library is loaded externally to make the app available in a single file.

Oh, I didn't anticipate that after reading that it's single file app.

>You are probably blocking requests to that resource, so you need to whitelist it.

Yes I am - under the impression that single file app means "completely single file" (i.e. with external libs inlined if any).

I can confirm it works if all external resources are allowed.
